init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

cache:
 - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # install latest dotnet core 3 preview
  #- cmd: choco install dotnet-6.0-sdk
  - cmd: dotnet tool install -g fake-cli
  - cmd: dotnet tool install -g paket
  # # Update npm
  # # There seems to be issues with npm 5.4 in Windows
  # # See https://github.com/npm/npm/issues/18380
  # - npm install -g npm@6.1.0

os: Visual Studio 2022

build_script:
  - cmd: fake build -t test

test: off